-- Schema for A.B.C. Music streaming service

DROP TABLE IF EXISTS song;
DROP TABLE IF EXISTS album;
DROP TABLE IF EXISTS artist;
DROP TABLE IF EXISTS genre;

CREATE TABLE song
(
    id     INTEGER PRIMARY KEY AUTOINCREMENT,
    title  VARCHAR(100) NOT NULL,
    length INTEGER NOT NULL
);

CREATE TABLE album
(
    id     INTEGER PRIMARY KEY AUTOINCREMENT,
    title  VARCHAR(100) NOT NULL,
    year   INTEGER NOT NULL
);

CREATE TABLE artist
(
    id   INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE genre
(
    id    INTEGER PRIMARY KEY AUTOINCREMENT,
    genre VARCHAR(20) UNIQUE
);
